export const carsConstants = {
    GET_ALL: 'GET_ALL',
    GET_MOST_CHEAPER: 'GET_MOST_CHEAPER',
    SHOWMODALEDIT: 'SHOWMODALEDIT',
    TOGGLEMODAL: 'TOGGLEMODAL',
    MODIFY_CAR_TO_EDIT:'MODIFY_CAR_TO_EDIT'
};
