export const configConstants = {
    CREATESUCCESS: 'CREATESUCCESS',
    CREATEFAIL: 'CREATEFAIL',
    UPDATESUCCESS: 'UPDATESUCCESS',
    UPDATEFAIL: 'UPDATEFAIL',
    ERASESUCCESS: 'ERASESUCCESS',
    ERASEFAIL: 'ERASEFAIL',
    ERASEMESSAGE:'ERASEMESSAGE',
    SHOWMESSAGE: 'SHOWMESSAGE'
}